version: '2'

services:
  odoo:
    build: odoo  # local development
    #image: emakital/avia-odoo
    entrypoint: ./entrypoint.sh
    command: openerp-server
    ports:
      - "8069:8069"
    depends_on:
      - db
    links: 
      - db
    volumes:
      - odoovol:/var/lib/odoo
      - extra:/mnt/extra-addons

  db:
    image: postgres:9.5
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
    volumes:
      - postgresdata:/var/lib/postgresql/data
volumes:
  odoovol:
  extra:
  postgresdata:
